" Put bundles here
Bundle 'tpope/vim-surround'
Bundle 'kien/ctrlp.vim'
Bundle 'Shougo/neosnippet.vim'
Bundle 'honza/vim-snippets'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'tpope/vim-repeat'
Bundle 'nathanaelkane/vim-indent-guides'
" Bundle 'mhinz/vim-startify.git'
Bundle 'tomtom/tcomment_vim'
Bundle 'matchit.zip'
Bundle 'ervandew/supertab'
Bundle 'Syntastic'
Bundle 'scrooloose/nerdtree'
" Bundle 'Lokaltog/powerline'
" Bundle 'Shougo/neocomplcache.vim'
Bundle 'myusuf3/numbers.vim'
